import React from 'react';
import FaqList from './FaqList';
import { Box, Flex, chakra } from '@chakra-ui/react';

const faqs = [
    {
        question: "What is FourQuant.ai?",
        answer: "FourQuant.ai is an advanced robo-trading platform that leverages cutting-edge AI and machine learning technologies to optimize and automate trading strategies. The platform is designed for both novice and experienced traders, providing powerful tools and algorithms that analyze vast amounts of market data in real-time, identify profitable trading opportunities, and execute trades with minimal human intervention. Whether you're trading stocks, forex, or cryptocurrencies, FourQuant.ai aims to enhance your trading efficiency and success."
    },
    {
        question: "How do I create an account on FourQuant.ai?",
        answer: "Creating an account on FourQuant.ai is a straightforward process. Start by clicking the 'Sign Up' button located on the homepage. You'll be prompted to enter your personal information, such as your name, email address, and phone number. Once you've filled in the required details, you'll need to verify your email address by clicking on the verification link sent to your inbox. After verification, you can set up your profile, link your bank account, and make your first deposit to start trading."
    },
    {
        question: "How does the robo-trading algorithm work?",
        answer: "The robo-trading algorithm at FourQuant.ai operates by continuously monitoring and analyzing market conditions across various assets. It uses complex mathematical models and machine learning techniques to predict price movements and identify optimal entry and exit points for trades. The algorithm can process a vast amount of data much faster than a human, enabling it to make decisions in milliseconds. Once a trading opportunity is identified, the algorithm automatically executes the trade, helping you capitalize on market movements without needing to constantly monitor the markets."
    },
    {
        question: "How do I withdraw my funds?",
        answer: "Withdrawing funds from your FourQuant.ai account is a seamless process. To begin, log in to your account and navigate to the 'Wallet' section. From there, you'll see an option to 'Withdraw Funds.' Click on it, and you'll be prompted to select the bank account you want to transfer the funds to, as well as the amount you'd like to withdraw. After confirming the details, your withdrawal request will be processed. Depending on your bank, it may take 1-3 business days for the funds to appear in your account."
    },
    {
        question: "What are the fees associated with using FourQuant.ai?",
        answer: "FourQuant.ai operates on a performance-based fee structure, which means you only pay a small percentage of the profits generated by the trades executed by our algorithms. This aligns our success with yours, ensuring that we are incentivized to help you make the most out of your investments. Additionally, there may be minimal fees for certain account types or services, such as withdrawals or premium features. Full details of our pricing and fees can be found in the 'Pricing' section on our website, where we provide a transparent breakdown of all potential costs."
    },
    {
        question: "Can I use FourQuant.ai on my mobile device?",
        answer: "Yes, FourQuant.ai is fully accessible on mobile devices through our dedicated mobile app, available for both iOS and Android. The app is designed to provide the same robust functionality as the desktop version, allowing you to monitor your portfolio, execute trades, and stay updated with market news on the go. The user interface is optimized for mobile, ensuring a smooth and intuitive experience. Whether you're at home or on the move, FourQuant.ai ensures you have full control over your trading activities."
    },
    {
        question: "How do I contact customer support?",
        answer: "At FourQuant.ai, we prioritize customer satisfaction and support. If you have any questions or encounter issues, our customer support team is here to assist you. You can reach out to us through several channels: visit the 'Contact Us' page on our website to send an email, initiate a conversation via our live chat feature, or call our dedicated support hotline. We also have an extensive help center with FAQs and troubleshooting guides that may address your concerns. Our team is available 24/7 to provide timely and efficient support."
    },
    {
        question: "What is the minimum deposit required to start trading?",
        answer: "The minimum deposit required to start trading on FourQuant.ai depends on the type of account you choose. Our platform offers various account tiers, each with different benefits and minimum deposit requirements. For example, our basic account may require a lower minimum deposit, ideal for beginners, while our premium accounts, which offer advanced features and personalized support, may require a higher initial deposit. Specific details regarding the minimum deposit for each account type can be found in the 'Account Types' section on our website."
    },
    {
        question: "How can I update my account information?",
        answer: "To update your account information, log in to your FourQuant.ai account and navigate to the 'Profile' section. Here, you can edit personal details such as your email address, phone number, and password. Additionally, you can update financial information, including linked bank accounts and payment methods. It is important to keep your account information up to date to ensure smooth transactions and communications. If you encounter any issues while updating your details, our customer support team is available to assist you."
    },
    {
        question: "Are there any restrictions on the markets or assets I can trade?",
        answer: "FourQuant.ai offers access to a wide range of markets and assets, including stocks, forex, commodities, and cryptocurrencies. However, certain restrictions may apply depending on your account type, geographical location, and regulatory requirements. For instance, some assets may only be available to higher-tier account holders, or certain markets may be restricted due to local regulations. We recommend reviewing the 'Market Access' section on our website to understand the full range of trading options available to you and any potential limitations."
    },
    {
        question: "What happens if there is a technical issue during a trade?",
        answer: "While FourQuant.ai is built with robust technology to ensure smooth operation, technical issues can occasionally arise. In the event of a technical problem during a trade, our system is designed to automatically activate fail-safe mechanisms to protect your investments. This may include halting trades temporarily or reverting to pre-determined safe positions. If you experience an issue, we recommend contacting our customer support immediately. Our team will investigate the problem and work to resolve it as quickly as possible, ensuring minimal disruption to your trading activities."
    },
    {
        question: "How secure is my data on FourQuant.ai?",
        answer: "Security is a top priority at FourQuant.ai. We employ industry-leading security measures to protect your personal and financial information. Our platform uses advanced encryption protocols to secure data transmission and storage. Additionally, we implement multi-factor authentication (MFA) for account access, ensuring that only authorized users can log in. Regular security audits are conducted to identify and address potential vulnerabilities. Rest assured that your data is safe with us, and we are committed to maintaining the highest standards of security."
    },
    {
        question: "Can I customize my trading strategy on FourQuant.ai?",
        answer: "Absolutely! FourQuant.ai allows you to customize your trading strategies based on your risk tolerance, investment goals, and market preferences. Whether you prefer a conservative approach or are looking for high-risk, high-reward opportunities, our platform offers a range of tools and settings to tailor the trading experience to your needs. You can adjust parameters such as stop-loss limits, trading frequency, and asset allocation. For advanced users, we offer features that enable the creation of custom algorithms, allowing for even greater control over your trading activities."
    },
    {
        question: "Does FourQuant.ai offer educational resources?",
        answer: "Yes, FourQuant.ai is dedicated to empowering our users with knowledge. We offer a comprehensive range of educational resources designed to help you understand the markets and improve your trading skills. Our resources include tutorials, webinars, articles, and market analysis from industry experts. Whether you're new to trading or looking to refine your strategies, our educational content is tailored to all skill levels. Access these resources through the 'Education' section on our platform and start enhancing your trading expertise today."
    },
    {
        question: "What are the benefits of using robo-trading over traditional trading methods?",
        answer: "Robo-trading, as offered by FourQuant.ai, presents several advantages over traditional trading methods. Firstly, it eliminates emotional decision-making, ensuring that trades are executed based on data and predefined strategies rather than impulses. Secondly, it operates 24/7, allowing you to take advantage of market opportunities even when you're not actively monitoring the markets. Additionally, robo-trading can process vast amounts of data at speeds that far exceed human capabilities, potentially leading to more accurate and profitable trades. These benefits, combined with the efficiency and convenience of automation, make robo-trading an attractive option for many traders."
    }
];

const Faq = () => {
    return (
        <Flex
            bg="#666db3"
            p={20}
            w="auto"
            justifyContent="center"
            alignItems="center"
        >
            <Box
                py={12}
                bg="white"
                rounded="xl"
                shadow="base"
                w="100%"
            >
                <Box maxW="7xl" mx="auto" px={{ base: 4, lg: 8 }}>
                    <Box textAlign="center">
                        <chakra.h2
                            mt={2}
                            fontSize={{ base: "3xl", sm: "4xl" }}
                            lineHeight="8"
                            fontWeight="extrabold"
                            letterSpacing="tight"
                            color="gray.900"
                        >
                            Frequently Asked Questions
                        </chakra.h2>
                        <chakra.p
                            mt={4}
                            maxW="2xl"
                            fontSize="xl"
                            mx={{ lg: "auto" }}
                            color="gray.500"
                        >
                            Discover answers to some of the most commonly asked questions
                        </chakra.p>
                    </Box>

                    <Box mt={10}>
                        <FaqList faqs={faqs} />
                    </Box>
                </Box>
            </Box>
        </Flex>
    );
};

export default Faq;
